---
author:
  - name: Francisco Damián Escobar Candelaria
    email: francisco.escobar30@unach.mx
    corresponding: true
    affiliations:
      - ref: unach
  - name: Yofre Hernán García Gómez
    degrees: PhD
    email: yofre.garcia@unach.mx
    roles: [supervision]
    affiliations:
      - ref: unach

affiliations:
  - id: unach
    name: Universidad Autónoma de Chiapas
---

# Resumen {.unnumbered}
::: {style="text-align: justify"}
Este trabajo explora el uso de DeepONet para resolver ecuaciones diferenciales parciales, aplicándola a la estimación de temperatura en tejidos biológicos mediante la ecuación del bio-calor, en contextos clínicos como la hipertermia oncológica.

Se comparó el desempeño de DeepONet frente a un método numérico clásico, como Crank-Nicolson, evaluando precisión mediante métricas de error. La red neuronal fue entrenada para resolver la EDP del Bio-Calor simplificandola de manera que no se tuviera en cuenta la fuente metabólica de calor $Q$.

Los resultados muestran que DeepONet puede aproximar la solución eficazmente en distintos tiempos, con ventajas de generalización respecto a redes PINN convencionales, posicionándose como una herramienta prometedora en el modelado térmico biomédico.


:::
