{
  "hash": "e4b3c1257c3aaf1a48275ea63d8d4930",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Comparación de resultados\nlang: es\nexecute: \n  freeze: auto\n---\n\n::: {style=\"text-align: justify\"}\n\n## Comparativa visual de las predicciones\nEsta sección presenta un análisis cualitativo de los resultados mediante la comparación directa entre las predicciones del modelo, las soluciones reportadas en el estudio de @medical_rep, así como las obtenidas mediante el método de Crank Nickolson y la solución analítica. La visualización paralela permite evaluar:\n\n- Dominio espacial: Cuadrado unitario [0,1] × [0,1] con malla 26×26.\n- Escala de colores: Mapa térmico YlGnBu y viridis (consistente en sus respectivos gráficos).\n\n### Modelo contra resultados de @medical_rep\nEl siguiente código grafica las predicciones de la red neuronal DeepONet para la temperatura dadas las coordenadas espaciales en los distintos tiempos de interés, los ejes están adimencionalizados siguiendo las ecuaciones -@eq-adimencionalizadores.\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nfrom mpl_toolkits.mplot3d import Axes3D\nimport matplotlib.gridspec as gridspec\nimport pandas as pd\nimport numpy as np\n\n# Lista de tiempos\ntimes = [0.0, 0.25, 0.5, 0.75, 1.0]\n\n# Cargar el dataframe\ndf = pd.read_csv(r'data/model_DoN.csv')  \n\n# Crear figura con subplots 3D en 1 fila y 5 columnas\nfig, axes = plt.subplots(nrows=1, ncols=len(times), \n                        figsize=(28, 7),\n                        subplot_kw={'projection': '3d'})\n\nplt.subplots_adjust(right=0.8)\n\n# Asumimos que el grid es regular\nnum_points = int(np.sqrt(df[df[\"time\"] == times[0]].shape[0]))\n\n# Lista para almacenar los objetos surface\nsurf_list = []\n\n# Reordenar para graficar\nfor i, (t_val, ax) in enumerate(zip(times, axes)):\n    # Filtrar por tiempo actual\n    df_t = df[df[\"time\"] == t_val]\n\n    # Obtener los valores de X, Y, Theta\n    X_vals = df_t[\"X\"].values.reshape((num_points, num_points))\n    Y_vals = df_t[\"Y\"].values.reshape((num_points, num_points))\n    Z_vals = df_t[\"Theta\"].values.reshape((num_points, num_points))\n\n    # Dibujar la superficie\n    surf = ax.plot_surface(\n        Y_vals, X_vals, Z_vals,\n        rstride=1, cstride=1,\n        cmap=\"YlGnBu\",\n        edgecolor=\"none\",\n        antialiased=True\n    )\n    surf_list.append(surf)\n\n    ax.set_title(f\"Time = {t_val:.2f}\", pad=10)\n    ax.set_xlabel(\"Y\", labelpad=10)\n    ax.set_ylabel(\"X\", labelpad=10)\n    ax.set_zlabel(\"T [θ]\", labelpad=10, rotation=90)\n    ax.set_box_aspect(None, zoom=0.75)\n\n# Añadir barra de color común\ncbar = fig.colorbar(surf_list[-1], ax=axes,\n                    shrink=0.9, aspect=90,\n                    pad=0.1, orientation='horizontal')\ncbar.set_label('Temperatura [θ]')\n\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Predicciones de la red neuronal a distintos tiempos.](comparaciones_files/figure-pdf/fig-my_results-output-1.pdf){#fig-my_results fig-pos='H'}\n:::\n:::\n\n\n![Resultados reportados por @medical_rep en el caso 2D.](images/results_paper.png){#fig-results_fnn fig-align=\"center\" width=\"650\"}\n\nLa comparación visual entre las predicciones del modelo DeepONet [@fig-my_results] y los resultados de @medical_rep [@fig-results_fnn] revela una notable similitud en la evolución temporal y espacial de la temperatura. Ambos modelos capturan la misma tendencia de calentamiento progresivo, con un gradiente térmico que se intensifica cerca de la frontera derecha ($x=1$), donde se aplica una condición de Neumann no homogénea. Sin embargo, se observa que en $t=0$, el modelo DeepONet se aproxima con mayor fidelidad al plano $XY=0$, lo que sugiere una mejor captura de la condición inicial en comparación con el trabajo de referencia.\n\n### Modelo contra método numérico\nLa siguiente gráfica utiliza los archivos csv obtenidos de los códigos [-@lst-modelo-don] y [-@lst-met-num] para motrar una comparativa entre los tiempos de interés, las predicciones del modelo se encuentran en la parte superior mientras que las del método numérico en la parte inferior.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\ncrank_nick_data = pd.read_csv(r'data/crank_nick.csv')\nmodel_don_data = pd.read_csv(r'data/model_DoN.csv')\n\n# Determinar los límites comunes para el colorbar\nmin_temp = min(model_don_data['Theta'].min(),\n                crank_nick_data['Theta'].min())\nmax_temp = max(model_don_data['Theta'].max(), \n                crank_nick_data['Theta'].max())\n\n# Crear figura con subplots 3D en 2 filas y 5 columnas\nfig = plt.figure(figsize=(22, 12))\naxes = []\n\n# Crear los subplots\nfor i in range(2):  # 2 filas\n    for j in range(5):  # 5 columnas\n        axes.append(fig.add_subplot(2, 5, i*5 + j + 1, projection='3d'))\n\naxes = np.array(axes).reshape(2, 5)\n\n# Añadir títulos generales para cada fila\nfig.text(0.5, 0.92, \"Predicciones modelo DON\", \n        ha='center', va='center', fontsize=14,fontweight='bold')\nfig.text(0.5, 0.58, \"Predicciones método numérico\",\n        ha='center', va='center', fontsize=14, fontweight='bold')\n\n# Función para graficar un dataframe en una fila específica\ndef plot_dataframe(df, row, num_points, cmap=\"viridis\"):\n    surf_list = []\n    for col, t_val in enumerate(times):\n        ax = axes[row, col]\n        \n        # Filtrar por tiempo actual\n        df_t = df[df[\"time\"] == t_val]\n\n        # Obtener los valores de X, Y, Theta\n        X_vals = df_t[\"X\"].values.reshape((num_points, num_points))\n        Y_vals = df_t[\"Y\"].values.reshape((num_points, num_points))\n        Z_vals = df_t[\"Theta\"].values.reshape((num_points, num_points))\n\n        # Dibujar la superficie con límites comunes\n        surf = ax.plot_surface(\n            Y_vals, X_vals, Z_vals,\n            rstride=1, cstride=1,\n            cmap=cmap,\n            edgecolor=\"none\",\n            antialiased=True,\n            vmin=min_temp,\n            vmax=max_temp\n        )\n        surf_list.append(surf)\n\n        ax.set_title(f\"Time = {t_val:.2f}\", pad=10)\n        ax.set_xlabel(\"Y\", labelpad=10)\n        ax.set_ylabel(\"X\", labelpad=10)\n        ax.set_zlabel(\"T [θ]\", labelpad=10, rotation=90)\n        ax.set_box_aspect(None, zoom=0.75)\n    \n    return surf_list\n\n# Asumimos que el grid es regular para ambos dataframes\nnum_points = int(np.sqrt(\n        model_don_data[model_don_data[\"time\"] == times[0]].shape[0]))\n\n# Graficar el primer dataframe en la fila superior\nsurf_model_don = plot_dataframe(model_don_data, 0, num_points)\n\n# Graficar el segundo dataframe en la fila inferior\nsurf_crank_nick = plot_dataframe(crank_nick_data, 1, num_points)\n\n# Añadir barra de color común en la parte inferior\ncbar = fig.colorbar(surf_crank_nick[-1], ax=axes.ravel().tolist(),\n                    use_gridspec=True, orientation='horizontal',\n                    pad=0.05, aspect=90, shrink=0.9)\ncbar.set_label('Temperatura [θ]', labelpad=10)\n\n\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Contraste de las predicciones entre el modelo y el método de Crank Nicolson para cada tiempo. Se aprecia que ambas comparten forma y tendencia, sin embargo a medida que el tiempo se acerca a t=1 los resultados divergen.](comparaciones_files/figure-pdf/fig-met-num-vs-model-output-1.pdf){#fig-met-num-vs-model fig-pos='H'}\n:::\n:::\n\n\nAl contrastar las predicciones del modelo con las obtenidas mediante el método de Crank-Nicolson [@fig-met-num-vs-model], se confirma que ambas soluciones comparten la misma estructura general y comportamiento temporal. No obstante, a medida que el tiempo avanza hacia $t=1$, se aprecia una ligera divergencia en la magnitud de la temperatura, especialmente en la región cercana a $x=1$, donde el gradiente impuesto introduce mayor sensibilidad numérica.\n\n### Modelo contra solución analítica\nLa siguiente gráfica utiliza los archivos csv obtenidos de los códigos [-@lst-modelo-don] y [-@lst-sol-ana] para mostrar una comparativa entre los tiempos de interés, las predicciones del modelo se encuentran en la parte superior mientras que las de la solución analítica en la parte inferior.\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\nsol_ana_data = pd.read_csv(r'data/sol_analitica.csv')\nmodel_don_data = pd.read_csv(r'data/model_DoN.csv')\n\n# Determinar los límites comunes para el colorbar\nmin_temp = min(model_don_data['Theta'].min(),\n                sol_ana_data['Theta'].min())\nmax_temp = max(model_don_data['Theta'].max(), \n                sol_ana_data['Theta'].max())\n\n# Crear figura con subplots 3D en 2 filas y 5 columnas\nfig = plt.figure(figsize=(22, 12))\naxes = []\n\n# Crear los subplots\nfor i in range(2):  # 2 filas\n    for j in range(5):  # 5 columnas\n        axes.append(fig.add_subplot(2, 5, i*5 + j + 1, projection='3d'))\n\naxes = np.array(axes).reshape(2, 5)\n\n# Añadir títulos generales para cada fila\nfig.text(0.5, 0.92, \"Predicciones modelo DON\", \n        ha='center', va='center', fontsize=14,fontweight='bold')\nfig.text(0.5, 0.58, \"Predicciones de la Sol. analítica\",\n        ha='center', va='center', fontsize=14, fontweight='bold')\n\n# Función para graficar un dataframe en una fila específica\ndef plot_dataframe(df, row, num_points, cmap=\"viridis\"):\n    surf_list = []\n    for col, t_val in enumerate(times):\n        ax = axes[row, col]\n        \n        # Filtrar por tiempo actual\n        df_t = df[df[\"time\"] == t_val]\n\n        # Obtener los valores de X, Y, Theta\n        X_vals = df_t[\"X\"].values.reshape((num_points, num_points))\n        Y_vals = df_t[\"Y\"].values.reshape((num_points, num_points))\n        Z_vals = df_t[\"Theta\"].values.reshape((num_points, num_points))\n\n        # Dibujar la superficie con límites comunes\n        surf = ax.plot_surface(\n            Y_vals, X_vals, Z_vals,\n            rstride=1, cstride=1,\n            cmap=cmap,\n            edgecolor=\"none\",\n            antialiased=True,\n            vmin=min_temp,\n            vmax=max_temp\n        )\n        surf_list.append(surf)\n\n        ax.set_title(f\"Time = {t_val:.2f}\", pad=10)\n        ax.set_xlabel(\"Y\", labelpad=10)\n        ax.set_ylabel(\"X\", labelpad=10)\n        ax.set_zlabel(\"T [θ]\", labelpad=10, rotation=90)\n        ax.set_box_aspect(None, zoom=0.75)\n    \n    return surf_list\n\n# Asumimos que el grid es regular para ambos dataframes\nnum_points = int(np.sqrt(\n        model_don_data[model_don_data[\"time\"] == times[0]].shape[0]))\n\n# Graficar el primer dataframe en la fila superior\nsurf_model_don = plot_dataframe(model_don_data, 0, num_points)\n\n# Graficar el segundo dataframe en la fila inferior\nsurf_crank_nick = plot_dataframe(sol_ana_data, 1, num_points)\n\n# Añadir barra de color común en la parte inferior\ncbar = fig.colorbar(surf_crank_nick[-1], ax=axes.ravel().tolist(),\n                    use_gridspec=True, orientation='horizontal',\n                    pad=0.05, aspect=90, shrink=0.9)\ncbar.set_label('Temperatura [θ]', labelpad=10)\n\n\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Contraste de las predicciones entre el modelo y la solución analítica para cada tiempo. Se aprecia que ambas comparten forma y tendencia, sin embargo a medida que el tiempo se acerca a t=1 los resultados divergen.](comparaciones_files/figure-pdf/fig-sol-ana-vs-model-output-1.pdf){#fig-sol-ana-vs-model fig-pos='H'}\n:::\n:::\n\n\nFinalmente, la comparación con la solución analítica [@fig-sol-ana-vs-model] refuerza la validez del modelo DeepONet. Aunque la forma general de la solución es consistentemente recuperada, se observa que las discrepancias aumentan levemente con el tiempo, lo cual es esperable dada la naturaleza truncada de la solución analítica y la aproximación inherente de la red neuronal.\n\n## Validaciones cuantitativas\n\n### Modelo contra el método de Crank-Nicolson\nPara evaluar numéricamente la precisión del modelo DeepONet, se realizó una comparación sistemática con soluciones de referencia generadas mediante el método de Crank-Nicolson. Este enfoque proporciona una métrica objetiva de la exactitud del modelo, siendo complementado con una serie de gráficos que muestran el error absoluto para cada punto del dominio en los tiempos de interés.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\n# Función para calcular errores\ndef calculate_errors(true_data, pred_data, times):\n    results = []\n    \n    for time in times:\n        # Filtrar datos por tiempo\n        true_subset = true_data[true_data['time'] == time]\n        pred_subset = pred_data[pred_data['time'] == time]\n        \n        if len(true_subset) == 0 or len(pred_subset) == 0:\n            print(f\"Advertencia: No hay datos para tiempo t={time}\")\n            continue\n        \n        # Verificar que las dimensiones coincidan\n        if len(true_subset) != len(pred_subset):\n            print(f\"Advertencia:Num de puntos no coincide para t={time}\")\n            min_len = min(len(true_subset), len(pred_subset))\n            true_subset = true_subset.iloc[:min_len]\n            pred_subset = pred_subset.iloc[:min_len]\n        \n        # Calcular errores para Theta\n        theta_true = true_subset['Theta'].values\n        theta_pred = pred_subset['Theta'].values\n        \n        absolute_error = np.abs(theta_true - theta_pred)\n        l2_error = np.sqrt(np.sum((theta_true - theta_pred)**2))\n        \n        results.append({\n            'time': time,\n            'mean_absolute_error': np.mean(absolute_error),\n            'max_absolute_error': np.max(absolute_error),\n            'l2_error': l2_error\n        })\n    \n    return pd.DataFrame(results)\n\n# Calcular errores\nerror_results = calculate_errors(crank_nick_data, model_don_data, times)\n\n# Guardar resultados\nerror_results.to_csv(\"data/error_crank_nic.csv\", index=False)\n```\n:::\n\n\n::: {#tbl-errores-num .cell tbl-cap='Desviación del modelo DeepONet respecto a Crank-Nicolson.' execution_count=5}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=5}\n|   Tiempo |   MAE |   MaxAE |   Error L2 |\n|---------:|------:|--------:|-----------:|\n|    0.000 | 0.013 |   0.058 |      0.467 |\n|    0.250 | 0.066 |   0.181 |      2.215 |\n|    0.500 | 0.069 |   0.154 |      2.166 |\n|    0.750 | 0.034 |   0.052 |      0.964 |\n|    1.000 | 0.028 |   0.110 |      1.067 |\n:::\n:::\n\n\nLas métricas de error calculadas —Error Absoluto Medio (MAE), Error Absoluto Máximo (MaxAE) y Error L2— confirman el buen desempeño del modelo DeepONet. En la comparación con el método de Crank-Nicolson [@tbl-errores-num], el MAE se mantuvo entre 0.013 y 0.069, con un valor máximo de 0.181 en el MaxAE. Estos valores reflejan una aproximación satisfactoria, aunque se observa que los errores tienden a aumentar en tiempos intermedios ($t=0.25$ y $t=0.5$), posiblemente debido a la mayor complejidad dinámica en esas etapas.\n\n#### Gráficas de error absoluto\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\n# Calcular el error absoluto entre los dos dataframes\nerror_data = model_don_data.copy()\nerror_data['error'] = np.abs(\n                    crank_nick_data['Theta'] - model_don_data['Theta'])\n\n# Crear figura con 3 filas y 2 columnas\nfig, axes = plt.subplots(nrows=1, ncols=5, figsize=(22, 8))\naxes = axes.ravel()  # Convertir a array 1D para fácil acceso\n\n# Asumir que el grid es regular\nnum_points = int(np.sqrt(\n                    error_data[error_data[\"time\"] == times[0]].shape[0]\n                    ))\n\n# Configuración común para los mapas de calor\nplot_kwargs = {\n    'cmap': 'hot_r',\n    'shading': 'auto',\n    'vmin': error_data['error'].min(),\n    'vmax': error_data['error'].max()\n}\n# Lista para guardar los gráficos\nabs_errors_pc = []\n\n# Crear los subplots\nfor i, t_val in enumerate(times):\n    ax = axes[i]\n    \n    # Filtrar por tiempo actual\n    df_t = error_data[error_data[\"time\"] == t_val]\n    \n    # Obtener valores y reshape\n    X_vals = df_t[\"X\"].values.reshape((num_points, num_points))\n    Y_vals = df_t[\"Y\"].values.reshape((num_points, num_points))\n    error_vals = df_t[\"error\"].values.reshape((num_points, num_points))\n    \n    # Crear mapa de calor\n    pc = ax.pcolormesh(X_vals, Y_vals, error_vals, **plot_kwargs)\n    \n    # Configuración de ejes\n    ax.set_title(f\"Tiempo = {t_val:.2f}\", pad=10)\n    ax.set_xlabel(\"X\")\n    ax.set_ylabel(\"Y\")\n    ax.set_aspect('equal')\n\n    abs_errors_pc.append(pc)\n\ncbar = fig.colorbar(abs_errors_pc[-1], ax=axes,\n                    use_gridspec=True, shrink=0.9,\n                    aspect=90, pad=0.1, orientation='horizontal')\ncbar.set_label('Error absoluto [θ]')\n\n# Mostrar el gráfico\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Errores absolutos entre el modelo y el método de Crank Nicolson para cada tiempo.](comparaciones_files/figure-pdf/fig-abs-errors-num-output-1.pdf){#fig-abs-errors-num fig-pos='H'}\n:::\n:::\n\n\n### Modelo contra la solución analítica\nDe manera análoga a la sección anterior se realizó una comparativa contra la solución analítica (@sec-sol-ana). De este modo se tiene una visión más completa acerca del rendimiento del modelo.\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\n# Función para calcular errores\ndef calculate_errors(true_data, pred_data, times):\n    results = []\n    \n    for time in times:\n        # Filtrar datos por tiempo\n        true_subset = true_data[true_data['time'] == time]\n        pred_subset = pred_data[pred_data['time'] == time]\n        \n        if len(true_subset) == 0 or len(pred_subset) == 0:\n            print(f\"Advertencia: No hay datos para tiempo t={time}\")\n            continue\n        \n        # Verificar que las dimensiones coincidan\n        if len(true_subset) != len(pred_subset):\n            print(f\"Advertencia:Num de puntos no coincide para t={time}\")\n            min_len = min(len(true_subset), len(pred_subset))\n            true_subset = true_subset.iloc[:min_len]\n            pred_subset = pred_subset.iloc[:min_len]\n        \n        # Calcular errores para Theta\n        theta_true = true_subset['Theta'].values\n        theta_pred = pred_subset['Theta'].values\n        \n        absolute_error = np.abs(theta_true - theta_pred)\n        l2_error = np.sqrt(np.sum((theta_true - theta_pred)**2))\n        \n        results.append({\n            'time': time,\n            'mean_absolute_error': np.mean(absolute_error),\n            'max_absolute_error': np.max(absolute_error),\n            'l2_error': l2_error\n        })\n    \n    return pd.DataFrame(results)\n\n# Calcular errores\nerror_results = calculate_errors(sol_ana_data, model_don_data, times)\n\n# Guardar resultados\nerror_results.to_csv(\"data/error_ana.csv\", index=False)\n```\n:::\n\n\n::: {#tbl-errores-ana .cell tbl-cap='Error del modelo DeepONet respecto a la solución analítica.' execution_count=8}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=8}\n|   Tiempo |   MAE |   MaxAE |   Error L2 |\n|---------:|------:|--------:|-----------:|\n|    0.000 | 0.013 |   0.058 |      0.467 |\n|    0.250 | 0.065 |   0.178 |      2.187 |\n|    0.500 | 0.067 |   0.149 |      2.104 |\n|    0.750 | 0.031 |   0.046 |      0.877 |\n|    1.000 | 0.032 |   0.119 |      1.181 |\n:::\n:::\n\n\nAl comparar con la solución analítica [@tbl-errores-ana], los errores son consistentemente bajos, con un MAE máximo de 0.067 y un MaxAE de 0.178. La similitud entre ambas tablas sugiere que el método de Crank-Nicolson y la solución analítica están bien alineados, y que el modelo DeepONet se aproxima a ambos con un nivel de error comparable.\n\n#### Gráficas de error absoluto\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\n# Calcular el error absoluto entre los dos dataframes\nerror_data = model_don_data.copy()\nerror_data['error'] = np.abs(\n                    sol_ana_data['Theta'] - model_don_data['Theta'])\n\n# Crear figura con 3 filas y 2 columnas\nfig, axes = plt.subplots(nrows=1, ncols=5, figsize=(22, 8))\naxes = axes.ravel()  # Convertir a array 1D para fácil acceso\n\n# Asumir que el grid es regular\nnum_points = int(np.sqrt(\n                    error_data[error_data[\"time\"] == times[0]].shape[0]\n                    ))\n\n# Configuración común para los mapas de calor\nplot_kwargs = {\n    'cmap': 'hot_r',\n    'shading': 'auto',\n    'vmin': error_data['error'].min(),\n    'vmax': error_data['error'].max()\n}\n# Lista para guardar los gráficos\nabs_errors_pc = []\n\n# Crear los subplots\nfor i, t_val in enumerate(times):\n    ax = axes[i]\n    \n    # Filtrar por tiempo actual\n    df_t = error_data[error_data[\"time\"] == t_val]\n    \n    # Obtener valores y reshape\n    X_vals = df_t[\"X\"].values.reshape((num_points, num_points))\n    Y_vals = df_t[\"Y\"].values.reshape((num_points, num_points))\n    error_vals = df_t[\"error\"].values.reshape((num_points, num_points))\n    \n    # Crear mapa de calor\n    pc = ax.pcolormesh(X_vals, Y_vals, error_vals, **plot_kwargs)\n    \n    # Configuración de ejes\n    ax.set_title(f\"Tiempo = {t_val:.2f}\", pad=10)\n    ax.set_xlabel(\"X\")\n    ax.set_ylabel(\"Y\")\n    ax.set_aspect('equal')\n\n    abs_errors_pc.append(pc)\n\ncbar = fig.colorbar(abs_errors_pc[-1], ax=axes,\n                    use_gridspec=True, shrink=0.9,\n                    aspect=90, pad=0.1, orientation='horizontal')\ncbar.set_label('Error absoluto [θ]')\n\n# Mostrar el gráfico\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Errores absolutos entre el modelo y la solución analítica para cada tiempo.](comparaciones_files/figure-pdf/fig-abs-errors-ana-output-1.pdf){#fig-abs-errors-ana fig-pos='H'}\n:::\n:::\n\n\nLos mapas de error absoluto [@fig-abs-errors-num] y [@fig-abs-errors-ana] permiten localizar espacialmente las discrepancias. Se observa que los mayores errores se concentran en la región de $x=1$, donde la condición de Neumann no homogénea introduce mayores exigencias en la aproximación. Esta distribución del error es coherente con el comportamiento reportado en la literatura para problemas con condiciones de frontera variables en el tiempo.\n:::\n\n",
    "supporting": [
      "comparaciones_files/figure-pdf"
    ],
    "filters": []
  }
}